import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Typography, Container } from "@mui/material";
import SpeedDial from "../components/speedDial";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Typography variant="h1" sx={{color:'#424244', fontWeight:'bold'}}>
          front
        </Typography>
        <Box sx={{ position: "absolute", bottom: "20px", right: "20px" }}>
          <SpeedDial />
        </Box>
      </main>
    </>
  );
}
